GoHawaiiForMe/backend

httpTest/plan.http
prisma/mock/plan.mock.ts
prisma/mock/user.mock.ts
prisma/prisma.seed.ts
src/app.module.ts
src/plan/plan.controller.ts
src/plan/plan.module.ts
src/plan/plan.repository.ts
src/plan/plan.service.ts

- close #8 
Plan 단일 조회 api 구현
-

Feat: #8 Plan 단일조회 구현

---

prisma/mock/dreamerProfile.mock.ts
prisma/mock/follow.mock.ts
prisma/mock/makerProfile.mock.ts
prisma/mock/plan.mock.ts
prisma/mock/user.mock.ts
prisma/prisma.seed.ts

- close #13 
목데이터 업데이트 및 seed.ts 수정
-

유저, 찜하기 mockdata 추가

---

prisma/migrations/20250107155118_add_coconut_field/migration.sql
prisma/mock/user.mock.ts
prisma/schema.prisma
src/common/enums/error.message.ts
src/user/domain/user.domain.ts
src/user/domain/user.mapper.ts
src/user/type/user.types.ts

- close #15 
유저 schema에 coconut 필드 추가
-

유저 schema 수정

---

src/common/filters/globalExceptionFilter.ts

Fix: #19 커스텀에러필터 수정

---

httpTest/plan.http
src/common/enums/error.message.ts
src/plan/plan.controller.ts
src/plan/plan.repository.ts
src/plan/plan.service.ts
src/plan/type/createPlanData.dto.ts
src/plan/type/createPlanData.interface.ts

Plan 생성 api 구현

---

httpTest/plan.http
prisma/migrations/20250109021530_plan_status_overdue/migration.sql
prisma/schema.prisma
src/common/enums/error.message.ts
src/common/types/status.type.ts
src/plan/plan.controller.ts
src/plan/plan.repository.ts
src/plan/plan.service.ts
src/plan/type/createPlanData.interface.ts
src/plan/type/updateAssignData.dto.ts
src/plan/type/updatePlanData.interface.ts

assign 컨트롤러, complete 컨트롤러 구현
- close #24 
assign 컨트롤러, complete 컨트롤러 구현
-

Plan Update api 구현

---

httpTest/plan.http
prisma/migrations/20250109040815_plan_title/migration.sql
prisma/mock/plan.mock.ts
prisma/schema.prisma
src/plan/plan.repository.ts
src/plan/type/createPlanData.dto.ts
src/plan/type/createPlanData.interface.ts
src/plan/type/planQueryOptions.dto.ts
src/plan/type/planQueryOptions.ts
src/plan/type/planWhereCondition.interface.ts

- close #27 
필터링 추가 및 검색조건 변경
-

Plan 목록조회 tripType 필터링 추가 및 검색조건 변경

---

httpTest/quote.http
httpTest/user.http
prisma/mock/quote.mock.ts
prisma/prisma.seed.ts
src/app.module.ts
src/common/enums/error.message.ts
src/common/filters/globalExceptionFilter.ts
src/quote/domain/quote.domain.ts
src/quote/domain/quote.interface.ts
src/quote/domain/quote.mapper.ts
src/quote/quote.controller.ts
src/quote/quote.module.ts
src/quote/quote.repository.ts
src/quote/quote.service.ts
src/quote/type/quote.mapper.properties.interface.ts
src/quote/type/quoteProperties.ts
src/quote/type/quoteToClientProperties.interface.ts

- close #26 
Quote 단일조회 구현
유저가 삭제됐을 경우 null 값 반환
접근권한은 해당 견적서의 Dreamer와 Maker로 제한(프론트에 확인 필요)
```
Content-Length: 759
ETag: W/"2f7-Y9nmIy6EsNz632O217UpWehe+R4"
Date: Thu, 09 Jan 2025 18:44:06 GMT
{
"id": "0b4b3eee-b4c7-485b-9d05-d0b3ba91ed1c",
"createdAt": "2023-10-01T10:00:00.000Z",
"updatedAt": "2023-10-01T10:10:00.000Z",
"price": 1000,
"content": "3일 간의 기본 여행 계획, 숙박과 항공권 포함.",
"plan": {
"id": "d7a56f8d-94b9-4b9d-8bdf-3b6295a3b3b4",
"createdAt": "2025-01-09T18:09:44.371Z",
"updatedAt": "2025-01-09T18:09:44.371Z",
"isDeletedAt": null,
"title": "제목1",
"startDate": "2025-01-10T00:00:00.000Z",
"endDate": "2025-01-10T09:00:00.000Z",
"tripType": "FOOD_TOUR",
"serviceArea": "SEOUL",
"details": …
```

Quote 단일조회 api 구현

---

httpTest/plan.http
httpTest/quote.http
prisma/mock/plan.mock.ts
prisma/prisma.seed.ts
src/common/enums/error.message.ts
src/common/utility/validateBooleanValue.ts
src/plan/plan.controller.ts
src/plan/plan.module.ts
src/plan/plan.repository.ts
src/plan/plan.service.ts
src/quote/domain/quote.mapper.ts
src/quote/quote.controller.ts
src/quote/quote.module.ts
src/quote/quote.repository.ts
src/quote/quote.service.ts
src/quote/type/quote.dto.ts
src/quote/type/quote.type.ts
src/quote/type/quoteProperties.ts

- close #40 
Quote 생성 api 구현
- `POST` plan/:planId/quotes
Maker의 견적 생성
- REQUEST
```jsx
POST /plans/8fc40908-9269-4db3-ad7d-fb6e69b0ba0d/quotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJpYXQiOjE3MzY2MDQ0MTEsImV4cCI6MTczNzIwOTIxMX0.-eqbbKywgkiLltw8lF7NOFxytanxIQTtRHQ8OEYkE3M
Content-Type: application/json
{
"price": "200",
"content": "제가 제일 잘해요"
}
```
- RESPONSE
```jsx
HTTP/1.1 201 Created
Access-Control-Allow-Origin: *
Content-Length: 314
ETag: W/"13a-PhUazOv6IFD7EkL0dnIvw7DU4/k"
Date: Sun, 12 Jan 2025 14:11:56 GMT
{
"id": "dbd345cd-506f-4795-93d3-c1321ec3bc0f",
"createdAt": "2025-01-12T14:11:56.393Z",
"updatedAt": …
```

Quote 생성 api 구현

---

httpTest/quote.http
httpTest/user.http
src/common/enums/error.message.ts
src/common/utility/validateBooleanValue.ts
src/plan/plan.service.ts
src/quote/domain/quote.domain.ts
src/quote/domain/quote.interface.ts
src/quote/domain/quote.mapper.ts
src/quote/quote.controller.ts
src/quote/quote.repository.ts
src/quote/quote.service.ts
src/quote/type/quote.dto.ts

- close #45 
- 견적 확정하기 api 구현
- `PATCH` quotes/:quotes
Dreamer의 견적 확정
- REQUEST
```jsx
PATCH http://localhost:4000/quotes/df36dc9c-288a-4db6-9ccf-7c80b1dbef9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NTVkNDYzZS0zN2I2LTQxMGItOTA2MS0xMWE5ZDY4MjJiZGQiLCJpYXQiOjE3MzY3NTM3NzgsImV4cCI6MTczNzM1ODU3OH0.us-Jbn1-Rb6Eiq0UCdLGSsGuZqy5dJL6Dix5xFdRoPA
Content-Type: application/json
{
"isConfirmed": true
}
```
- df36dc9c-288a-4db6-9ccf-7c80b1dbef9e는 견적서의 id
- isConfirmed는 옵셔널이기 떄문에 바디 없이 요청할 수 있음
- RESPONSE
```jsx
Access-Control-Allow-Origin: *
Content-Length: 222
ETag: W/"de-xJu8fVoDfdsGAxEYFqoQZ8pbhZw"
Date: Mon, 13 Jan 2025 08:04:26 GMT
{
"id": …
```

Feat: #45 견적 확정하기 api 구현

---

httpTest/plan.http
src/common/constants/errorMessage.enum.ts
src/common/types/plan/plan.dto.ts
src/common/types/plan/plan.type.ts
src/common/utilities/validateBooleanValue.ts
src/modules/plan/plan.controller.ts
src/modules/plan/plan.repository.ts
src/modules/plan/plan.service.ts
src/providers/database/prisma/mock/plan.mock.ts

- close #63 
지정견적 요청을 받은 플랜 필터링 옵션 넣기
- Plan 리스트 조회(Maker) `GET` /plans/
- REQUEST
```jsx
GET http://localhost:4000/plans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3MzY4OTk4NDgsImV4cCI6MTczNjk4NjI0OH0.cnv6k5TdsIT3pNPB0KtPiioCqWGrJKltloe8Ry1gGkM
orderBy=SCHEDULE_FIRST&tripType=SHOPPING&pageSize=3&page=2
```
- RESPONSE
```jsx
Access-Control-Allow-Origin: *
Content-Length: 896
ETag: W/"380-YHQT/hu3aGaVhCYdgXU7Y5mEXNk"
Date: Wed, 15 Jan 2025 00:17:30 GMT
{
"totalCount": 1,
"list": [
{
"id": "7d37a0b0-23e2-4509-b478-1256a2a41d8d",
"createdAt": "2025-01-14T13:40:55.157Z",
"updatedAt": …
```

지정견적 요청 받은 플랜 필터링 추가

---

src/modules/userStats/userStats.controller.ts
src/modules/userStats/userStats.module.ts
src/modules/userStats/userStats.repository.ts
src/modules/userStats/userStats.service.ts
src/providers/database/mongoose/userStats.schema.ts

- close #73 
mongoose로 유저(Maker) 활동을 기록할 UserStats 모델을 생성합니다.
스키마 내용
```
model UserStats {
id
userId
averageRating // 별점 평균
totalReviews // 리뷰 총 갯수
totalConfirmedPlans // 플랜 확정 총 갯수
totalFavorites  // 찜한 총 갯수
createdAt 
updatedAt 
}
```
-

UserStats 모델 생성

---

.env.example
package-lock.json
package.json
src/app.module.ts
src/modules/userStats/userStats.service.ts
src/providers/cache/bullmq.module.ts
src/providers/cache/bullmq.processor.ts
src/providers/cache/redis.service.ts

- close #71
Redis 연결 및 모듈, 서비스 생성
-

Redis 설정 세팅

---

.env.example
src/app.module.ts
src/providers/cache/bullmq.module.ts

- close #82 
Redis를 Render가 아닌 로컬로 설정을 변경합니다.
-

Redis 배포 설정 변경

---

src/main.ts

- close #86 
쿠키를 저장을 위해 CORS 설정을 추가합니다.
-

쿠키 저장을 위한 CORS 설정

---

src/main.ts

- close #86 
해당 이슈에 추가 변경 사항 올립니다!
localhost:3000으로 설정하니 테스트가 좀 어려워서, 개발 기간 동안만 모든 오리진 허용으로 설정해 두려고 합니다.
-

모든 오리진 허용으로 설정 변경

---

httpTest/plan.http
package-lock.json
package.json
src/app.module.ts
src/common/domains/plan/plan.domain.ts
src/common/domains/plan/plan.interface.ts
src/common/types/plan/plan.type.ts
src/modules/plan/plan.module.ts
src/modules/plan/plan.repository.ts
src/modules/plan/plan.service.ts
src/modules/task/task.module.ts
src/modules/task/tasks.service.ts

- close #81 
매일 자정에 스케줄러로 OVERDUE와 COMPLETE로 자동변경 해주고 작업
스케줄러는 당일이 될 경우 OVERDUE로 변경,
COMPLETE는 일주일의 여유기간을 두고 COMPLETE로 변경
-

매일 자정에 스케줄러로 플랜의 상태 업데이트 구현

---

src/app.module.ts
src/common/domains/userStats/userStats.domain.ts
src/common/domains/userStats/userStats.interface.ts
src/common/domains/userStats/userStats.mapper.ts
src/common/types/userStats/userStats.types.ts
src/modules/userStats/userStats.controller.ts
src/modules/userStats/userStats.module.ts
src/modules/userStats/userStats.repository.ts
src/modules/userStats/userStats.service.ts

- close #89 
데이터 조회를 위한 getById 메서드 구현 (API X, 내부에서 사용할 메서드)
-

UserStats 조회 메서드 구현

---

src/common/domains/userStats/userStats.domain.ts
src/common/domains/userStats/userStats.interface.ts
src/modules/userStats/userStats.controller.ts
src/modules/userStats/userStats.repository.ts
src/modules/userStats/userStats.service.ts

- close #92 
UserStats 데이터 업데이트 시 기존 데이터가 없는 경우 생성하는 메서드를 통합하여 구현합니다.
- 생성되는 UserStats 데이터 예시

UserStats 업데이트 및 생성 메서드 구현

---

src/common/domains/notification/notification.domain.ts
src/common/domains/notification/notification.mapper.ts
src/common/types/notification/notification.types.ts
src/modules/notification/notification.listener.ts
src/modules/notification/notification.repository.ts
src/modules/notification/notification.service.ts
src/modules/plan/plan.service.ts
src/providers/database/mongoose/notification.schema.ts

- close #101 
프론트엔드와 상의 후에 알림 메시지 구성을 변경하여 스키마를 수정하고 반환 값을 수정합니다.
-

알림 메시지 구성 수정

---

src/common/domains/follow/follow.mapper.ts
src/common/types/follow/follow.types.ts
src/common/types/user/user.types.ts
src/modules/follow/follow.repository.ts

- close #105 
찜한 Maker 목록 조회(getFollowList) 응답에 Maker의 ServiceType 필드를 추가합니다.
```
{
"totalCount": 2,
"list": [
{
"id": "1c05a5ab-e311-4266-885d-d9b1c2096fc8",
"makerId": "6b4ded82-e680-410d-b86d-ce6974e53f37",
"maker": {
"nickName": "무궁화",
"image": "DEFAULT_1",
"gallery": "https://www.instagram.com/codeit_kr/",
"serviceTypes": [
"RELAXATION",
"SHOPPING"
],
"averageRating": 5,
"totalReviews": 4,
"totalFollows": 4,
"totalConfirms": 3
},
"dreamerId": "555d463e-37b6-410b-9061-11a9d6822bdd",
"isFollowed": true
},
{
"id": "1ce3cc3a-c7c4-4442-9e5c-6cafb3b1e219",
"makerId": "a08d9856-adfa-4f83-9e9a-48401f3d0ef3",
"maker": {
"nickName": "개나리",
"image": "DEFAULT_2",
"gallery": "https://www.instagram.com/codeit_kr/",
"serviceTypes": [
"RELAXATION",
"SHOPPING"
],
"averageRating": 4,
"totalReviews": …
```

찜한 Maker 목록 조회 ServiceType 필드 추가

---

src/common/types/chat/chat.type.ts
src/modules/chat/chat.repository.ts
src/modules/chat/chat.service.ts
src/modules/chatRoom/chatRoom.controller.ts
src/modules/chatRoom/chatRoom.service.ts

- close #118
채팅 기록 가져오기 api 구현
<html>
<body>
<ul>
<li>chat 기록 가져오기 <code>GET</code> chatRooms/:chatRoomId/chats
<ul>
<li>
<p>REQUEST</p>
<pre><code class="language-jsx">GET &lt;http://localhost:4000/chatRooms/67933592d9d1b4a0ed4dccc9/chats?page=1&amp;pageSize=5&gt;
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc4MDk3NjEsImV4cCI6MTczNzg5NjE2MX0.OcH8161EdtCh0DGj_phKWp2CLjyY-ZZ05-8e4n38VOU
</code></pre>
</li>
<li>
<p>RESPONSE</p>
<pre><code class="language-jsx">HTTP/1.1 200 OK
Vary: Origin
Content-Length: 1135
ETag: W/&quot;46f-i4mZpVXb8K2XVDY14XIcIGXkaWk&quot;
Date: Sat, 25 …

채팅 기록 가져오기 구현

---

src/common/domains/follow/follow.domain.ts
src/common/domains/follow/follow.interface.ts
src/common/domains/follow/follow.mapper.ts
src/common/types/follow/follow.types.ts
src/modules/follow/follow.module.ts
src/modules/follow/follow.repository.ts
src/modules/follow/follow.service.ts
src/modules/review/review.repository.ts

- close #110 
찜하기 로직(service) 내에서 찜한 Maker의 UserStats 업데이트 작업을 큐에 등록합니다.
-

찜한 Maker의 UserStats 업데이트 작업 큐 등록

---

src/common/types/plan/plan.type.ts
src/modules/plan/plan.repository.ts

- close #120
maker의 플랜 리스트에서 내가 견적을 쓴 플랜은 보이지 않도록 필터링
-

maker의 플랜 리스트에서 내가 견적을 쓴 플랜은 보이지 않도록 필터링

---

src/common/domains/user/user.domain.ts
src/common/domains/user/user.mapper.ts
src/common/types/user/user.response.dto.ts
src/common/types/user/user.types.ts
src/modules/user/user.controller.ts
src/modules/user/user.repository.ts
src/modules/user/user.service.ts

- close #126 
isFollowed 필드가 누락되어 추가 작업했습니다.
- getProfileCardData 반환 데이터 예시
```
{
nickName: '아카시아',
image: 'DEFAULT_3',
gallery: 'https://www.instagram.com/codeit_kr/',
serviceTypes: [ 'RELAXATION', 'SHOPPING' ],
isFollowed: true,
averageRating: 5,
totalReviews: 3,
totalFollows: 4,
totalConfirms: 3
}
```

유저 프로필카드 데이터 불러오는 메서드 생성 - isFollowed 필드 추가

---

src/common/constants/errorMessage.enum.ts
src/common/domains/user/user.domain.ts
src/modules/user/user.service.ts

- close #131 
유저 프로필 수정 시 프론트엔드에서 비밀번호 입력 오류는 에러 코드를 400으로 달라고 요청해서 수정합니다.
- 너무 간단해서 이슈로 나누기도 애매한데, 작업 내용이 달라서 일단 따로 만들었습니다 😅

비밀번호 입력 오류에 대한 에러 코드 수정

---

src/common/domains/chatRoom/chatRoom.properties.ts
src/modules/chatRoom/chatRoom.controller.ts
src/modules/chatRoom/chatRoom.module.ts
src/modules/chatRoom/chatRoom.service.ts

- close #137 
- 채팅방 목록조회 `GET` /chatRooms
- REQUEST
```jsx
GET /chatRooms
```
- RESPONSE
```
Vary: Origin
Content-Length: 307
ETag: W/"133-Anc6aMklCAcqQdIctED76CWyPWg"
Date: Fri, 24 Jan 2025 06:28:43 GMT
{
"totalCount": 1,
"list": [
{
"id": "67933318ad420bd3608dca00",
"createdAt": "2025-01-24T06:28:40.137Z",
"updatedAt": "2025-01-24T06:28:40.137Z",
"userIds": [
"66885a3c-50f4-427b-8a92-3702c6976fb0",
"032d7bd4-116c-467b-9352-a14b0d494ef9"
],
"planId": "9004bc52-a8b0-4587-af53-59914168582f",
"lastChat": null,
"isActive": true
}
]
}
```
변경 후
```jsx
Vary: Origin
Content-Type: …
```

채팅방 api 리스폰스에 유저정보를 추가

---

src/common/domains/chatRoom/chatRoom.domain.ts
src/common/domains/chatRoom/chatRoom.interface.ts
src/common/types/chat/chat.type.ts
src/modules/chat/chat.module.ts
src/modules/chatRoom/chatRoom.gateway.ts
src/modules/chatRoom/chatRoom.module.ts
src/modules/chatRoom/chatRoom.repository.ts
src/modules/chatRoom/chatRoom.service.ts

Feat: #139 채팅방 입장 구현

---

nginx/default.conf
nginx/nginx.conf

- close #144 
Nginx 설정을 공유하기 위한 config 파일을 프로젝트에 추가합니다.
-

Nginx Config 파일 추가

---

src/common/constants/errorMessage.enum.ts
src/common/domains/chat/chat.domain.ts
src/common/domains/chat/chat.interface.ts
src/common/domains/chat/chat.properties.ts
src/common/types/chat/chatRoom.type.ts/chatRoom.typs.ts
src/modules/chat/chat.gateway.ts
src/modules/chat/chat.module.ts
src/modules/chat/chat.service.ts
src/modules/chatRoom/chatRoom.controller.ts
src/modules/chatRoom/chatRoom.gateway.ts
src/modules/chatRoom/chatRoom.repository.ts
src/modules/chatRoom/chatRoom.service.ts
src/modules/quote/quote.service.ts

- close #149 
채팅메시지 송수신 기능 구현
- 채팅 송수신
요청 URL
```jsx
ws://example.com
```
Header
- 토큰
MessageBody
```jsx
{
"chatRoomId": "67a00e38124c71b4723163e4",
"content": "메이커2의 채팅"
}
```
Event
```jsx
ClientToServerMessage //클라이언트에서 서버로 메시지 보내는 이벤트
ServerToClientMessage //서버에서 클라이언트로 메시지 보내는 이벤트
```
- 포스트맨 예시
- 에러 상황
- 해당 채팅방의 유저가 아닌 경우 403 에러
- 해당 채팅방이 없는 경우 404 에러

채팅메시지 송수신 기능 구현

---

src/modules/notification/notification.controller.ts

- close #157 
프론트엔드 요청 사항으로 테스트용 알림 생성 API를 구현합니다.
-

클라이언트 테스트용 알림 생성 API (2)

---

src/common/guards/webSocket.guard.ts

- close #161 
토큰이 넘어오지 않아 연결이 되지 않음 그래서 받는 방식 수정
-

웹소켓 토큰 추출방식 변경

---

src/common/constants/oauth.type.ts
src/common/domains/user/user.domain.ts
src/common/types/user/signup.dto.ts
src/common/types/user/user.types.ts
src/modules/auth/auth.service.ts
src/modules/auth/strategy/google.strategy.ts

- close #170 
OAuth 최초 로그인 시 유저 정보(role, nickName, phoneNumber) 추가와 프로필 생성을 위해 기존 로직을 수정합니다.
-

회원가입 로직 수정

---

.env.example
src/common/constants/oauth.type.ts
src/common/domains/user/user.domain.ts
src/common/types/user/user.types.ts
src/providers/database/prisma/migrations/20250207010518_add_provider_enum/migration.sql
src/providers/database/prisma/schema.prisma

유저 관련 타입 오류 해결

---

src/app.module.ts
src/common/constants/errorMessage.enum.ts
src/common/constants/pointEvent.type.ts
src/common/domains/pointLog/pointLog.domain.ts
src/common/domains/pointLog/pointLog.interface.ts
src/common/domains/pointLog/pointLog.mapper.ts
src/common/domains/user/user.domain.ts
src/common/domains/user/user.interface.ts
src/common/types/pointLog/pointLog.dto.ts
src/common/types/pointLog/pointLog.type.ts
src/modules/payment/payment.module.ts
src/modules/payment/payment.repository.ts
src/modules/payment/payment.service.ts
src/modules/pointLog/pointLog.controller.ts
src/modules/pointLog/pointLog.module.ts
src/modules/pointLog/pointLog.repository.ts
src/modules/pointLog/pointLog.service.ts
src/modules/task/task.module.ts
src/modules/task/tasks.service.ts
src/modules/user/user.service.ts
src/providers/database/mongoose/pointLog.schema.ts
src/providers/queue/bullmq.module.ts
src/providers/queue/pointLog.processor.ts
src/providers/queue/userStats.processor.ts

- close #189 
코코넛 변경 사항을 남기는 포인트 로그 테이블을 생성하고, 이벤트 발생시 로그에 기록하도록 구현합니다.
결제와 관련된 코코넛 충전 로직을 먼저 구현하고, 다음 이슈에서 플랜 생성 및 완료 로직에도 추가할 예정입니다.
bullmq를 활용해 비동기로 포인트 업데이트 및 로그를 생성하고, db 오류인 경우 자정에 scheduler를 통해 재시도 합니다.
-

포인트 충전 로직 구현

---

src/modules/quote/quote.service.ts

포인트 차감 및 전달 구현

---

package.json
src/modules/auth/auth.e2e.spec.ts
src/modules/review/review.controller.ts
src/modules/review/review.e2e.spec.ts
src/providers/database/prisma/mock/test.mock.ts

- close #219 
Review 모듈 테스트 코드 구현
- 
| File | $ Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
|--|--|--|--|--|--|
src/modules/review                     |   95.12 |      100 |   76.47 |     100 |                                      
review.controller.ts                  |     100 |      100 |     100 |     100 |                                      
review.module.ts                      |     100 |      100 |     100 |     100 |                                      
review.repository.ts                  |    92.3 |      100 |   71.42 |     100 |                                      
review.service.ts                     |   93.54 |      100 |   66.66 |     100 |

Review 모듈 e2e 테스트 코드

---

src/common/domains/user/user.domain.ts
src/common/domains/user/user.interface.ts
src/common/types/user/updateUser.dto.ts
src/modules/follow/follow.e2e.spec.ts
src/modules/user/user.e2e.spec.ts
src/modules/user/user.repository.ts
src/modules/user/user.service.ts
src/providers/database/prisma/mock/test.mock.ts

- close #218 
User 모듈 테스트 코드 구현
- 유저 정보 수정(update)에 문제가 있어 코드 수정했습니다.
- service의 124-125줄은 지금 follow 목데이터가 없어서 map이 실행되지 않아서인데... 이것 때문에 일부러 목데이터를 추가해야할지 고민되네요.
| File | $ Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
|--|--|--|--|--|--|
src/modules/user                       |   96.32 |    66.66 |   96.77 |   96.03 |                                                      
user.controller.ts                    |     100 |       60 |     100 |     100 | 44-88                                                
user.module.ts                        |     100 |      100 |     100 |     100 |                                                      
user.repository.ts                    |   95.12 |    61.11 |     100 |   94.73 | 57-58 …

User 모듈 e2e 테스트 코드

---

src/providers/database/prisma/mock/userStats.mock.ts

- close #237 
UserStats 목데이터를 추가합니다.
-

UserStats 목데이터 추가

---

package-lock.json
package.json
src/common/logger/log.middleware.ts
src/common/logger/logger.ts
src/main.ts

- close #236 
애플리케이션 로그를 수집하기 위해 winston을 설치하고 AWS CloudWatch에 로그를 전송하도록 설정합니다.
-

winston 설치 및 설정

---

httpTest/chat.http
httpTest/plan.http
src/app.module.ts
src/common/decorators/transaction.decorator.ts
src/modules/chat/chat.repository.ts
src/modules/chat/chat.service.ts
src/modules/chatRoom/chatRoom.service.ts
src/modules/plan/plan.repository.ts
src/modules/plan/plan.service.ts
src/providers/database/mongoose/config/mongo.config.ts
src/providers/database/mongoose/mock/chat.mock.ts
src/providers/database/transaction/transaction.manager.ts
src/providers/database/transaction/transaction.module.ts

- close #231 
트랜즈액션 데코레이터 구현
-

트랜즈액션 데코레이터 구현

---

src/modules/plan/plan.repository.ts
src/providers/database/transaction/transaction.manager.ts

- close #243 
Plan getPrismaClient 에러 해결
-

Plan getPrismaClient 에러 해결

---

src/modules/payment/domain/payment.mapper.ts
src/modules/payment/payment.service.ts
src/modules/review/types/review.dto.ts
src/modules/review/types/review.types.ts
src/providers/database/mongoose/payment.schema.ts

- close #250 
Swagger 페이지 접속 오류를 해결합니다.
-

Swagger 접속 오류 해결 및 코드 수정

---

src/providers/database/transaction/transaction.manager.ts

- close #252
몽구스는 옵셔널 줄 필요 없겠다 생각했는데 소켓통신은 als에 몽고세션이 있을 수가 없어서 프리즈마처럼 옵셔널 추가했습니다.
-

채팅방 소켓통신 연결 에러 해결

---

src/common/filters/globalExceptionFilter.ts
src/common/logger/winston/log.middleware.ts

- close #263 
어떤 에러가 발생했는지 테이블로 나타내기 위해 에러 메시지를 로그 수집에 포함시킵니다.
-

로그 데이터에 에러 메시지 추가
