- httpTest/quote.http
- httpTest/user.http
- src/common/enums/error.message.ts
- src/common/filters/globalExceptionFilter.ts
- src/common/types/status.type.ts
- src/plan/plan.controller.ts
- src/plan/plan.module.ts
- src/plan/plan.service.ts
- src/quote/domain/quote.mapper.ts
- src/quote/quote.controller.ts
- src/quote/quote.module.ts
- src/quote/quote.repository.ts
- src/quote/quote.service.ts
- src/quote/type/quote.mapper.properties.interface.ts
- src/quote/type/quoteQueryOptions.interface.ts
- close #32 
- Dreamer의 본인 플랜에 대한 견적 조회
```jsx
GET plans/:planId/quotes
옵셔널:  page, pageSize
response
{
"totalCount": 3,
"list": [
{
"id": "e00fce11-75bb-400a-99da-24ef6ca0e2c3",
"createdAt": "2023-10-03T09:15:00.000Z",
"updatedAt": "2023-10-03T09:45:00.000Z",
"price": 2000,
"content": "7일 간의 일본 그룹 투어, 단체 할인 적용.",
"maker": {
"id": "b3c4d5e6-f789-0123-4567-890abcdef123",
"role": "MAKER",
"nickName": "개나리",
"coconut": 1000
},
"isConfirmed": true,
"isAssigned": true
},
{
"id": "be7f1e1c-5192-4fa7-9e5e-8e228a8d8038",
"createdAt": "2023-10-02T12:00:00.000Z",
"updatedAt": "2023-10-02T12:30:00.000Z",
"price": 1500,
"content": "5일 간의 고급 투어 패키지, 프리미엄 호텔과 독점적인 경험 포함.",
"maker": null,
"isConfirmed": false,
"isAssigned": true
}
]
}
```
- planId : Param
- page: 기본값 1
- pageSize: 기본값 2
- Dreamer가 본인의 …
> Dreamer의 본인 플랜의 견적 조회 api 구현

- httpTest/quote.http
- src/quote/quote.service.ts
- src/quote/type/quote.dto.ts
- src/quote/type/quote.type.ts
- close #41 
드리머의 견적 목록 조회에서 isConfirmed 쿼리를 추가
확정된 견적만 리스폰스로 돌려주게함
디폴트는 false
```jsx
GET plans/:planId/quotes
예시 plans/:planId/quotes?isConfirmed=true
예시 plans/:planId/quotes?page=2&pageSize=2
response
{
"totalCount": 3,
"list": [
{
"id": "e00fce11-75bb-400a-99da-24ef6ca0e2c3",
"createdAt": "2023-10-03T09:15:00.000Z",
"updatedAt": "2023-10-03T09:45:00.000Z",
"price": 2000,
"content": "7일 간의 일본 그룹 투어, 단체 할인 적용.",
"maker": {
"id": "b3c4d5e6-f789-0123-4567-890abcdef123",
"role": "MAKER",
"nickName": "개나리",
"coconut": 1000
},
"isConfirmed": true,
"isAssigned": true
},
{
"id": "be7f1e1c-5192-4fa7-9e5e-8e228a8d8038",
"createdAt": "2023-10-02T12:00:00.000Z",
"updatedAt": "2023-10-02T12:30:00.000Z",
"price": 1500,
"content": "5일 간의 고급 투어 패키지, 프리미엄 호텔과 독점적인 경험 포함.",
"maker": null,
"isConfirmed": …
```
> Feat: #41 isConfirmed 옵셔널 필드 추가

- mongoose/notification.schema.ts
- src/notification/notification.controller.ts
- src/notification/notification.event.ts
- src/notification/notification.listener.ts
- src/notification/notification.module.ts
- src/notification/notification.service.ts
- src/plan/plan.service.ts
- close #33 
알림 이벤트 설정 및 지정 견적 요청시 알림 발송 추가
- 지정 견적 API 관련 수정사항 및 궁금한 점(?) 주석으로 남겨놓았습니다!
- 추후 eventEmitter로 같은 형식으로 알림 데이터 저장 및 실시간 발송할 수 있도록 테스트 완료했습니다!
> 지정 견적 요청시 maker에게 알림 발송하기

- httpTest/user.http
- src/common/enums/error.message.ts
- src/decorator/cookie.decorator.ts
- src/user/domain/user.domain.ts
- src/user/domain/user.interface.ts
- src/user/type/updateUser.dto.ts
- src/user/type/user.types.ts
- src/user/user.controller.ts
- src/user/user.service.ts
- close #48 
유저 정보 수정 시 기존 비밀번호와 대조 및 새 비밀번호와 확인용 비밀번호 일치 여부 확인 기능 추가
- User domain 수정 및 반환 타입 수정했습니다.
- 각각 password, newPassword, confirmNewPassword로 추가했습니다.
- 추가 커밋 : 쿠키 데코레이터 수정 및 토큰 재발급 코드 리팩토링
> 유저 정보 수정 시 비밀번호 확인 기능 추가

- src/modules/user/user.controller.ts
- src/modules/user/user.service.ts
- close #61 
기존 데이터베이스에서 이메일, 닉네임 중복 확인하는 API를 각각 구현합니다
- 존재하는 이메일/닉네임일 경우 false, 사용가능한 경우 true를 반환합니다.
> 회원가입시 이메일, 닉네임 중복 확인 API 구현

- package-lock.json
- package.json
- src/app.module.ts
- src/common/constants/errorMessage.enum.ts
- src/common/constants/paymentStatus.type.ts
- src/common/domains/payment/payment.domain.ts
- src/common/domains/payment/payment.interface.ts
- src/common/domains/payment/payment.mapper.ts
- src/common/types/payment/payment.type.ts
- src/modules/payment/payment.controller.ts
- src/modules/payment/payment.module.ts
- src/modules/payment/payment.repository.ts
- src/modules/payment/payment.service.ts
- src/providers/database/mongoose/payment.schema.ts
- src/providers/portOne/portone.module.ts
- src/providers/portOne/portone.provider.ts
- src/providers/portOne/portone.service.ts
- close #58 
결제 생성 및 결제 상태 조회 API 구현
- portOne provider 설정이 너무 오래 걸릴 것 같은데, 이것 때문에 타입 에러가 나서 작업해놓은 결제 완료 API(실제 결제 정보 연동 필요) 내용은 지우고 올립니다. 추후 다시 이어서 작업할 예정이라 provider 쪽 내용은 무시하셔도 되고, app.module.ts와 payment.module.ts 모두 연결하지 않은 상태입니다. 
- 결제 완료 API 및 웹훅 모두 추후 작업 예정
> 결제 생성 및 결제 상태 조회 API

- src/common/domains/follow/follow.domain.ts
- src/common/domains/follow/follow.interface.ts
- src/common/domains/follow/follow.mapper.ts
- src/common/domains/userStats/userStats.domain.ts
- src/common/domains/userStats/userStats.interface.ts
- src/common/types/follow/follow.dto.ts
- src/common/types/follow/follow.types.ts
- src/common/types/user/user.types.ts
- src/modules/follow/follow.controller.ts
- src/modules/follow/follow.module.ts
- src/modules/follow/follow.repository.ts
- src/modules/follow/follow.service.ts
- src/modules/userStats/userStats.module.ts
- src/modules/userStats/userStats.service.ts
- src/providers/cache/bullmq.processor.ts
- close #70 
유저가 찜한 Maker를 목록을 조회합니다.
**[GET] /follow?page=1&pageSize=10** (페이지네이션 기본값)
```
{
"totalCount": 2,
"list": [
{
"id": "0aae2257-53e2-4d88-b408-d885f56a3dff",
"makerId": "6b4ded82-e680-410d-b86d-ce6974e53f37",
"maker": {
"nickName": "무궁화",
"image": "DEFAULT_1",
"gallery": "https://www.instagram.com/codeit_kr/",
"averageRating": 5,
"totalReviews": 3,
"totalFollows": 4,
"totalConfirms": 3
},
"dreamerId": "555d463e-37b6-410b-9061-11a9d6822bdd",
"isFollowed": true
},
{
"id": "712e71af-be01-4bb9-992f-c66d6a10c5e7",
"makerId": "a08d9856-adfa-4f83-9e9a-48401f3d0ef3",
"maker": {
"nickName": "개나리",
"image": "DEFAULT_2",
"gallery": "https://www.instagram.com/codeit_kr/",
"averageRating": 4,
"totalReviews": 1,
"totalFollows": 5,
"totalConfirms": 2
},
"dreamerId": …
```
> 유저가 찜한 Maker 목록 조회 API 구현

- src/common/domains/review/review.domain.ts
- src/common/domains/review/review.interface.ts
- src/common/domains/review/review.mapper.ts
- src/common/types/follow/follow.types.ts
- src/common/types/review/review.dto.ts
- src/common/types/review/review.types.ts
- src/common/types/user/user.types.ts
- src/modules/review/review.controller.ts
- src/modules/review/review.repository.ts
- src/modules/review/review.service.ts
- close #107 
Maker에게 작성된 리뷰 목록을 조회하는 API를 구현합니다.
- 지난 PR 리뷰에 이야기한 '리뷰 생성 API' 응답 데이터 반환도 수정했습니다.
```
{
"totalCount": 2,
"groupByCount": [
{
"rating": 4,
"count": 2
}
],
"list": [
{
"id": "919ddc45-5d2c-4efa-8c5d-5e7f8c6838d2",
"writer": {
"nickName": "하마"
},
"rating": 4,
"content": "완벽한 대리 여행이었어요! 덕분에 좋은 경험이었습니다 :)",
"createdAt": "2025-01-23T12:35:23.970Z"
},
{
"id": "c48f3180-50ad-46be-9643-41a4664e6a7f",
"writer": {
"nickName": "호랑이"
},
"rating": 4,
"content": "완벽한 대리 여행이었어요! 덕분에 좋은 경험이었습니다 :)",
"createdAt": "2025-01-23T12:50:57.574Z"
}
]
}
```
> Maker 리뷰 목록 조회 API 구현

- src/common/domains/review/review.domain.ts
- src/common/domains/review/review.interface.ts
- src/common/domains/review/review.mapper.ts
- src/common/types/review/review.dto.ts
- src/common/types/review/review.types.ts
- src/modules/review/review.controller.ts
- src/modules/review/review.repository.ts
- src/modules/review/review.service.ts
- close #108 
내가 작성한 리뷰 목록을 조회하는 API를 구현합니다.
- 이전에 만든 review repository getByUser 메서드를 통합 사용할 수 있도록 수정했습니다
```
{
"totalCount": 3,
"list": [
{
"id": "919ddc45-5d2c-4efa-8c5d-5e7f8c6838d2",
"owner": {
"nickName": "무궁화",
"makerProfile": {
"image": "DEFAULT_1"
}
},
"plan": {
"tripType": "FOOD_TOUR",
"tripDate": "2024-11-26T00:00:00.000Z",
"quotes": [
{
"price": 175,
"isAssigned": false
}
]
},
"rating": 4,
"content": "완벽한 대리 여행이었어요! 덕분에 좋은 경험이었습니다 :)",
"createdAt": "2025-01-23T12:35:23.970Z"
}, ...
]
}
```
> 내가 작성한 리뷰 목록 조회 API 구현

- src/common/domains/plan/plan.domain.ts
- src/common/domains/plan/plan.interface.ts
- src/common/types/notification/notification.types.ts
- src/modules/notification/notification.service.ts
- src/modules/plan/plan.service.ts
- close #122 
플랜 취소로 인한 Maker에 견적 취소 알림과
지정견적 요청 반려로 인한 Dreamer에 견적 취소 알림,
견적 생성시 Dreamer에 견적 도착 알림을 추가합니다.
- 가능하면 plan에서 모두 알림을 추가하려고 했는데, 견적 확정시 plan 상태 업데이트 코드를 찾지 못해서 견적 확정 알림은 다음 PR에 올리겠습니다!
- 스케줄러를 이용한 여행일 알림도 다음 PR에 올리겠습니다.
> 비즈니스 로직 내 유저 알림 발송 추가

- src/common/domains/follow/follow.domain.ts
- src/common/domains/follow/follow.interface.ts
- src/common/domains/follow/follow.mapper.ts
- src/common/domains/user/user.domain.ts
- src/common/domains/user/user.interface.ts
- src/common/domains/user/user.mapper.ts
- src/common/types/follow/follow.types.ts
- src/common/types/user/query.dto.ts
- src/common/types/user/user.response.dto.ts
- src/common/types/user/user.types.ts
- src/modules/follow/follow.controller.ts
- src/modules/follow/follow.module.ts
- src/modules/follow/follow.repository.ts
- src/modules/follow/follow.service.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.module.ts
- src/modules/user/user.repository.ts
- src/modules/user/user.service.ts
- close #126 
유저 프로필카드에 들어가는 데이터를 공통적으로 조회하는 메서드를 생성합니다.
- user 라우트를 /users로 변경
- get follows: [GET] /users/following
```
{
"totalCount": 3,
"list": [
{
"id": "298d6acb-b2dd-445e-be53-34bc6e7db569",
"makerId": "ef846519-2b73-4be4-807e-f6ef1c07eb60",
"dreamerId": "66885a3c-50f4-427b-8a92-3702c6976fb0",
"createdAt": "2025-01-25T13:49:42.825Z",
"updatedAt": "2025-01-25T13:49:42.825Z",
"maker": {
"nickName": "아카시아",
"image": "DEFAULT_3",
"gallery": "https://www.instagram.com/codeit_kr/",
"serviceTypes": [
"RELAXATION",
"SHOPPING"
],
"averageRating": 5,
"totalReviews": 3,
"totalFollows": 4,
"totalConfirms": 3
}
}, ...
]
}
```
> 유저 프로필카드 데이터 불러오는 메서드 생성

- src/common/types/quote/quote.type.ts
- src/common/types/quote/quoteProperties.ts
- src/modules/quote/quote.repository.ts
- close #127
Quote 도메인 안에서 PlanReference를 가지게 되면서 잘못 수정하면서 생긴 오류 해결
- Quote 단일 조회(Maker) `GET` /quotes/:quoteId
- REQUEST
```jsx
GET /quotes/:quoteId
GET http://localhost:4000/quotes/b9063bfc-6282-4435-b512-944a4ffd19ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc4OTk2NTYsImV4cCI6MTczNzk4NjA1Nn0.NCd3kpAb84ktM8c2nApmD6StsoljqGCH04WgF5BvqeM
```
- RESPONSE
```jsx
Vary: Origin
Content-Length: 644
ETag: W/"284-/lAoh97mpn0H9dh25+VJ4NkcCdw"
Date: Sun, 26 Jan 2025 14:47:19 GMT
{
"id": "b9063bfc-6282-4435-b512-944a4ffd19ac",
"createdAt": …
```
> 견적서 단일조회 api 오류 해결

- src/common/decorators/user.decorator.ts
- src/common/domains/user/user.domain.ts
- src/common/domains/user/user.interface.ts
- src/common/guards/user.guard.ts
- src/common/types/user/profile.types.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.repository.ts
- src/modules/user/user.service.ts
- close #133 
Maker 상세페이지에서 userStats 데이터가 필요해서 userStats 포함한 프로필 조회 API를 추가합니다.
- 응답 예시
```
{
"nickName": "장미",
"image": "DEFAULT_4",
"gallery": "https://www.instagram.com/codeit_kr/",
"serviceTypes": [
"RELAXATION",
"SHOPPING"
],
"serviceArea": [
"SEOUL"
],
"description": "여행의 꿈을 대신 이루어 드립니다!",
"detailDescription": "안녕하세요! 여행을 좋아하고, 저희 지역을 소개하고 싶은 드림 메이커입니다 :) 드리머 여러분이 꿈꾸는 여행을 대신해서 이루어 드릴게요!",
"isFollowed": true,
"averageRating": 5,
"totalReviews": 1,
"totalFollows": 0,
"totalConfirms": 0
}
```
> 메이커 ID를 통한 프로필 조회 API 생성

- src/providers/database/prisma/mock/plan.mock.ts
- src/providers/database/prisma/mock/quote.mock.ts
- src/providers/database/prisma/mock/review.mock.ts
- src/providers/database/prisma/mock/userStats.mock.ts
- src/providers/database/prisma/prisma.seed.ts
- close #159 
리뷰 목데이터를 추가합니다.
- userStats 목데이터는 별도로 정리해서 추가할 예정이고, 프론트엔드 작업을 위해 maker1 데이터만 임시로 추가합니다.
> 리뷰 목데이터 추가

- .env.example
- package-lock.json
- package.json
- src/common/constants/errorMessage.enum.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.module.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/strategy/google.strategy.ts
- src/modules/auth/strategy/kakao.strategy.ts
- close #168 
카카오 간편 로그인 구현
- AuthService의 socialLogin 메서드를 하나로 통합
> 카카오 간편로그인 API 구현

- src/modules/auth/auth.controller.ts
- close #181 
간편 로그인시 서버에서 리다이렉트 할 때 CORS 문제가 발생하여, 클라이언트에서 로그인 후 서버로 콜백하는 로직을 수정합니다.
-
> 간편 로그인 로직 수정

- httpTest/chat.http
- src/common/constants/errorMessage.enum.ts
- src/common/domains/chat/chat.domain.ts
- src/common/domains/chat/chat.interface.ts
- src/common/domains/chat/chat.mapper.ts
- src/common/domains/chat/chat.properties.ts
- src/common/types/chatRoom/chatRoom.type.ts
- src/main.ts
- src/modules/chat/chat.controller.ts
- src/modules/chat/chat.module.ts
- src/modules/chat/chat.repository.ts
- src/modules/chat/chat.service.ts
- src/modules/chatRoom/chatRoom.repository.ts
- src/modules/chatRoom/chatRoom.service.ts
- close #176 
채팅 메시지 삭제
- 채팅 삭제 `DELETE` chats/:chatId
- REQUEST
```jsx
DELETE http://localhost:4000/chats/67a5be40d80a6a8eb3a6c3cf
Authorization: Bearer {{DREAMER1_TOKEN}}
```
- RESPONSE
```jsx
HTTP/1.1 204 No Content
Vary: Origin
Date: Fri, 07 Feb 2025 08:03:28 GMT
```
- 파라미터
Params
- chatId: string
- 참고사항
- 삭제기능이 생기면서 채팅 메시지 GET 메소드 리스폰스에는 isDeleted: boolean 필드가 생김
- 삭제가 될경우 클라이언트에는 내용을 바꿔서 전달해줌
- 삭제된 메시지입니다.
- 삭제된 이미지입니다.
- 삭제된 영상입니다.
- 서버에는 메시지 데이터 그대로 보존하고 있음
- 에러상황
- 해당 채팅이 없는 채팅인 경우 404에러
- 해당 채팅방의 isActive가 false인 경우 400 에러
- 이미 삭제된 채팅인 경우 409에러
> 채팅 메시지 삭제 구현

- src/common/domains/user/user.domain.ts
- src/common/domains/user/user.mapper.ts
- close #184 
준배님이 검색어 쿼리 관련 오류 이슈를 전달하셔서 확인했는데, 디버깅 하다보니 쿼리 문제가 아니라 UserStats 값이 없는 경우 도메인에서 반환할 때 오류가 나는 문제였습니다.. 일단 임시로 UserStats가 없을 경우 0을 반환하도록 처리하고, UserStats 목데이터 추가 후에 원상복구 하겠습니다.
-
> 메이커 목록 조회 API 검색어 쿼리 수정

- package-lock.json
- package.json
- src/common/constants/errorMessage.enum.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.module.ts
- src/modules/auth/auth.repository.ts
- src/modules/auth/auth.service.ts
- src/modules/auth/strategy/naver.strategy.ts
- src/providers/database/prisma/migrations/20250208182614_add_index/migration.sql
- src/providers/database/prisma/schema.prisma
- close #169 
- close #190 
네이버 간편 로그인을 구현하고, 회원가입 요청 시 유저와 프로필 데이터와 함께 header로 OAuthToken을 받아 provider, providerId 값에 적용하도록 로직을 추가합니다.
- provider에 따라 providerId가 중복되는 경우가 생길 수 있어, 기존에 providerId: @unique -> @@index([provider, providerId])로 변경했습니다. 두 필드가 모두 중복인 경우를 막아줍니다.
- 추가하는 김에 다른 인덱스도 추가하고, userId를 @unique -> @id로 수정했습니다. @id가 쿼리 처리에 훨씬 빠르기 때문에 이게 더 효율적인 것 같습니다!
> 네이버 간편로그인 API 및 간편로그인 유저 생성 로직 구현

- src/modules/user/user.controller.ts
- src/modules/user/user.repository.ts
- src/modules/user/user.service.ts
- close #194 
- close #195 
작업 내용이 많지 않아, 한 PR에 함께 올립니다.
- 찜한 메이커 목록 조회 시 maker profile의 description 필드를 포함시킵니다.
- 로그인한 유저가 메이커 목록 전체 조회 요청할 때 내가 찜한 메이커인지 확인 후 isFollwed 필드에 boolean 값을 응답에 포함합니다.
-
> 메이커 관련 조회 응답 내용 수정

- src/common/constants/errorMessage.enum.ts
- src/common/domains/plan/plan.domain.ts
- src/common/domains/plan/plan.interface.ts
- src/common/domains/quote/quote.domain.ts
- src/common/domains/quote/quote.interface.ts
- src/modules/plan/plan.module.ts
- src/modules/plan/plan.repository.ts
- src/modules/plan/plan.service.ts
- src/modules/quote/quote.module.ts
- src/modules/quote/quote.service.ts
- close #201 
- 플랜 견적 확정 시 견적 금액에 맞춰 Dreamer의 포인트 차감
- 플랜 완료 시 Maker에게 포인트 부여
-
> 포인트 차감 및 전달 구현

- httpTest/plan.http
- src/common/constants/groupByField.enum.ts
- src/common/types/plan/plan.dto.ts
- src/common/types/plan/plan.type.ts
- src/modules/plan/plan.controller.ts
- src/modules/plan/plan.repository.ts
- src/modules/plan/plan.service.ts
- close #202 
1. 지역 그룹별 카운팅 구현
2. 지역을 쿼리로 받으면 서비스 그룹별 카운팅 구현
- Plan 지역별 카운팅 `GET` /plans/serviceArea-group-count
- REQUEST
```tsx
GET http://localhost:4000/plans/serviceArea-group-count
```
- RESPONSE
```tsx
Vary: Origin
Content-Length: 107
ETag: W/"6b-K4gpkbFVt2TjjEL/plKwpWhJE0c"
Date: Wed, 12 Feb 2025 02:36:22 GMT
{
"totalCount": 54,
"groupByCount": [
{
"serviceArea": "GYEONGGI",
"count": 14
},
{
"serviceArea": "SEOUL",
"count": 40
}
]
}
```
- 참고사항
- 비로그인 시에도 사용할 수 있다.
- Plan tripType별 카운팅 `GET` /plans/tripType-group-count/:serviceArea
- REQUEST
```tsx
GET http://localhost:4000/plans/tripType-group-count/SEOUL
```
- RESPONSE
```tsx …
```
> 지역그룹별 카운팅 및 지역의 서비스 타입 그룹별 카운팅 api 구현

- httpTest/quote.http
- package.json
- src/common/domains/quote/quote.domain.ts
- src/common/types/quote/quote.dto.ts
- src/modules/plan/plan.e2e.spec.ts
- src/modules/quote/quote.e2e.spec.ts
- src/modules/quote/quote.repository.ts
- src/providers/database/prisma/DB.client.ts
- src/providers/database/prisma/mock/test.mock.ts
- close #211 
견적 모듈 테스트파일 구현
PASS  src/modules/quote/quote.e2e.spec.ts (32.109 s)
QuoteController (e2e)
[GET /plans/{planId}/quotes]
√ 드리머가 보는 해당 플랜의 견적 리스트 (2729 ms)
√ 본인이 아닌 플랜의 견적을 보려고 할 때 403에러 (729 ms)
√ 없는 플랜의 견적 리스트를 보려고 할 때 404에러 (109 ms)
[GET /quotes]
√ 메이커의 견적 리스트 보기 (550 ms)
√ 메이커의 견적 리스트를 드리머가 요청한다면 403에러 (24 ms)
√ 메이커의 견적 리스트에서 isSent 쿼리를 누락할 경우 400에러 (17 ms)
[GET /quotes/{quoteId} 견적 단일조회
√ 견적 단일 조회 (457 ms)
√ 권한이 없는 견적 단일 조회할 경우 403 에러 (357 ms)
√ 없는 견적의 id로 단일 조회할 경우 404 에러 (112 ms)
[POST /plans/{planId}/quotes]
√ 견적 생성하기 (1515 ms)
√ 없는 플랜의 id로 견적 생성할 경우 404 에러 (111 ms)
√ 이미 나의 견적이 있는 플랜에 견적 생성 요청을 할 경우 409 에러 (450 ms)
√ 메이커가 아닌경우 403에러 (20 ms)
[PATCH /quotes/{quoteId}/confirm]
√ 견적 확정하기 (1773 ms)
√ 견적 확정하기 요청 시 isConfirmed쿼리에 true를 제외하고 값을 넣을 경우 400에러 (21 ms)
√ 해당 견적이 없는데 …
> 견적 모듈 테스트파일 구현

- package.json
- src/common/domains/user/user.domain.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/auth.e2e.spec.ts
- src/modules/auth/auth.service.ts
- src/providers/database/prisma/DB.client.ts
- src/providers/database/prisma/mock/test.mock.ts
- close #217
Auth 모듈 테스트 코드 구현
- controller의 coverage가 높지 않은 이유는 auth.controller에 만든 소셜 로그인의 콜백 API의 경우 브라우저에서 구글 등에 직접 로그인 후 토큰을 받아서 처리하기 때문에 직접 테스트가 불가하기 때문입니다. 추후에 모킹해서 테스트 추가하겠습니다~!
| File | $ Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
|--|--|--|--|--|--|
|src/modules/auth                       |   83.33 |    53.33 |   79.31 |   82.89 |      |                                                         
|  auth.controller.ts                    |   77.27 |       40 |      75 |   76.19 | 74-90,104-118,134-148  |                  
|  auth.module.ts                        |     100 |      100 |     100 |     100 |        |                                                       
|  auth.repository.ts                    |   81.81 |      100 |      75 |      80 | 27-29,58-70   | …
> Auth 모듈 e2e 테스트 코드

- package.json
- src/modules/chatRoom/chatRoom.e2e.spec.ts
- close #213 
PASS  src/modules/chatRoom/chatRoom.e2e.spec.ts (17.138 s)
ChatRoom Test (e2e)
[GET /chatRooms]
√ 나의 채팅방 목록 조회 (1301 ms)
√ 나의 채팅방 목록 조회, 유효한 토큰이 오지 않을 경우 401에러 (18 ms)
[GET /chatRooms/{chatRoomId}]
√ 채팅방 단일조회 (388 ms)
√ 채팅방 단일조회, 유효한 토큰이 아닌 경우 401에러 (14 ms)
√ 채팅방 단일조회, 채팅방에 대한 권한이 없을 경우 403에러 (35 ms)
----------------------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------
File                                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------------------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------
All files                               |   51.74 |    10.37 |   20.93 | …
> 채팅방 모듈 테스트 파일 구현

- src/common/domains/notification/notification.mapper.ts
- src/modules/notification/notification.controller.ts
- src/modules/notification/notification.e2e.spec.ts
- src/modules/notification/notification.repository.ts
- src/providers/database/mongoose/mock/notification.mock.ts
- src/providers/database/mongoose/mongoose.seed.ts
- src/providers/database/mongoose/notification.schema.ts
- close #228 
Notification 모듈 테스트 코드 구현
- 알림의 경우 생성을 내부에서 진행하기 때문에 다른 모듈에서 테스트 되기 때문에 이번 커버리지가 낮습니다. controller의 경우 sse 연결 테스트는 생략했습니다. 참고해주세요.
| File | $ Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
|--|--|--|--|--|--|
src/modules/notification               |   71.42 |      100 |   40.62 |   67.44 |                                                                
notification.controller.ts            |   76.19 |      100 |   42.85 |   73.68 | 14,23,43-46                                                    
notification.listener.ts              |   88.88 |      100 |      50 |   85.71 | 11                                                             
notification.module.ts                |     100 |      100 |     100 |     100 | …
> Notification 모듈 e2e 테스트 코드

- src/common/constants/errorMessage.enum.ts
- src/modules/plan/plan.service.ts
- close #254 
서비스 지역이 다른 메이커에게는 지정견적을 신청하지 못하도록 막아둔건 그대로 유지중.
가정하는 상황은 "지정견적 요청을 받은 이후 메이커가 서비스지역을 수정할 경우 지정견적요청은 그래도 보여야한다."
이 상황을 위해 수정
-
> 지정견적 리스트는 메이커의 지역과 상관 없이 필터되지 않도록 수정

- src/modules/chatRoom/chatRoom.service.ts
- src/modules/plan/plan.service.ts
- close #257
플랜 완료시 생기는 에러 해결
플랜 완료시 해당 플랜의 채팅방이 없는 경우 에러가 생기므로 일단 수정합니다.
트랜젝션도 트랜젝션 적용 이슈에서 모두 해결하겠습니다.
-
> 플랜 완료시 채팅방이 존재하지 않아 생기는 에러 해결

- src/modules/auth/auth.controller.ts
- close #259 
프론트엔드와의 프록시 설정에 맞게 refreshToken을 브라우저 쿠키 저장할 때 보안 설정을 수정합니다.
-
> 토큰 set cookie 설정 수정

- src/modules/notification/notification.controller.ts
- close #265 
SSE는 서버의 단방향 통신의 특성상 일정 시간 동안 이벤트가 발생하지 않을 경우 연결이 끊깁니다.
NginX 설정만으로 해결해보려고 했지만..... SSE 특성상 HTTP 연결 유지 시키는 것만으로는 안되네요.
이 문제를 해결하기 위해 한 번 연결한 stream으로 주기적으로 빈 객체를 푸시하는 heartbeat 방식을 추가 설정합니다.
-
> SSE 연결 끊김 오류 해결

- src/modules/chat/chat.repository.ts
- src/modules/chat/chat.service.ts
- src/modules/chatRoom/chatRoom.repository.ts
- src/modules/chatRoom/chatRoom.service.ts
- src/modules/chatRoom/domain/chatRoom.domain.ts
- src/modules/chatRoom/domain/chatRoom.interface.ts
- src/modules/chatRoom/domain/chatRoom.properties.ts
- src/modules/plan/plan.service.ts
- src/modules/quote/quote.repository.ts
- src/modules/quote/quote.service.ts
- src/providers/database/mongoose/config/mongo.config.ts
- src/providers/database/transaction/transaction.manager.ts
- close #256 
transaction 적용
-
> transaction 적용
